# The Aggregate Nutrient Density Index Scores (ANDI)
# H= N/C (Health = Nutrients divided by Calories)
andi_scores = {
    'vegetables': {
        'leafy_green_vegetables': {
            'Kale': 1000,
            'Collard Greens': 1000,
            'Mustard Greens': 1000,
            'Swiss Chard': 895,
            'Bok Choy': 865,
            'Spinach': 707,
            'Arugula': 604,
            'Romaine Lettuce': None,
            'Iceberg Lettuce': None,
        },
        'solid_green_vegetables': {
            'Chinese Cabbage': 714,
            'Broccoli': 669,
            'Cabbage': 238,
            'Brussels Sprouts': 490,
            'Asparagus': 205,
            'Green Peas': None,
            'Green Beans': None,
            'Zucchini': None,
        },
        'non_green_vegetables': {
            'Radishes': 554,
            'Onions': 136,
            'Bell Peppers': 265,
            'Mushrooms': 238,
            'Tomatoes': 186,
            'Cauliflower': 315,
            'Carrots': None,
            'Cucumber': None,
            'Garlic': None,
            'Potatoes': None,
        },
    },
    'fruits': {
        'Strawberries': 212,
        'Pomegranate': 193,
        'Blackberries': 178,
        'Plums': 157,
        'Raspberries': 145,
        'Blueberries': 130,
        'Papaya': 118,
        'Oranges': 109,
        'Cantaloupe': 100,
        'Apples': None,
        'Bananas': None,
        'Peaches': None,
        'Pears': None,
        'Pineapple': None,
        'Grapes': None,
        'Mangoes': None,
        'Watermelon': None,
    },
    'beans_and_legumes': {
        'Lentils': 104,
        'Pinto Beans': 101,
        'Kidney Beans': 100,
        'Black Beans': 100,
        'Chickpeas': 78,
        'Soybeans': None,
        'Navy Beans': None,
        'Peas': None,
        'Lima Beans': None,
    },
    'nuts_and_seeds': {
        'Flaxseeds': 103,
        'Chia Seeds': 101,
        'Sesame Seeds': 74,
        'Sunflower Seeds': 78,
        'Almonds': 46,
        'Brazil Nuts & Pecans': 124,
        'Pistachio Nuts, unsalted': 48,
        'Almonds & Peanuts, unsalted': 38,
        'Walnuts': 34,
        'Hazelnuts or filberts': 32,
        'Cashew Nuts, unsalted': 27,
        'Pine Nuts/Pignolia': 26,
        'Macadamia nuts, unsalted': 17,
        'Flax Seeds & Sesame Seeds': 65,
        'Pumpkin Seeds': 52,
        'Peanuts': None,
    },
    'whole_grains_and_potatoes': {
        'Oats': 53,
        'Brown Rice': 41,
        'Quinoa': 21,
        'Whole Wheat': 17,
        'Barley(Gerste)': 43,
        'Bran Flakes': 64,
        'Wild Rice, cooked': 43,
        'Sprouted Grain Bread': 39,
        'Whole Grain Bread': 30,
        'Whole Wheat Bagel': 25,
        'Granola': 22,
        'Cornmeal, whole grain': 22,
        'Rye Bread': 20,
        'Whole Wheat Pasta, cooked': 19,
        'Oats, quick, cooked': 19,
        'White Bread & White Pasta': 18,
        'Couscous, cooked': 15,
        'Tortilla, flour/corn': 14,
        'White Rice & Rice Cakes': 12,
        'Potatoes': None,
        'Sweet Potatoes': None,
        'Buckwheat': None,
        'Amaranth': None,
        'Sorghum(Hirse)': None,
    },
    'dairy': {
        'Milk, low fat 1%': 28,
        'Plain Yogurt, low fat': 24,
        'Chocolate Milk': 19,
        'Fruit Yogurt, low fat': 15,
        'Cheese, hard': 15,
        'Cottage Cheese': 13,
        'Ice Cream/ Frozen Yogurt': 9,
        'Butter': None,
        'Cream': None,
        'Sour Cream': None,
        'Greek yogurt':None,
        'Egg':27,
    },
    'dairy_substitutes': {
        'Soy Milk': 33,
        'Almond Milk': 19,
        'Rice Milk': 10,
        'Oat Milk': None,
        'Coconut Milk': None,
    },
    'fast_food': {
        'Cheese Pizza': 17,
        'Fast Food Cheeseburger': 11,
        'French Fried Potatoes': 7,
    },
    'snack_foods': {
        'Dark Chocolate Candy Bar': 34,
        'Milk Chocolate Candy Bar': 21,
        'Popcorn, air popped, no salt': 16,
        'Hard pretzels, salted': 13,
        'Chocolate Pudding': 11,
        'Granola Bar': 11,
        'Potato Chips & Corn Chips': 10,
        'Chocolate chip cookies, ready to eat': 7,
        'Gummy Bears': None,
        'Crackers': None,
        'Rice Cakes': None,
        'Ice Cream': None,
    },
    'alcohol': {
        'Beer': 7,
        'Wine': 3,
    }
}


andi_recommendations = {
    'vegetables': {
        'percentage': {
            'minimum': 30,
            'maximum': 60,
        },
        'note': 'Half raw, half cooked.',
    },
    'fruits': {
        'percentage': {
            'minimum': 10,
            'maximum': 40,
        },
        'note': '3–5 servings of fresh fruit daily.',
    },
    'beans_and_legumes': {
        'percentage': {
            'minimum': 10,
            'maximum': 40,
        },
        'note': 'At least 85 grams daily.',
    },
    'nuts_and_seeds': {
        'percentage': {
            'minimum': 10,
            'maximum': 40,
        },
        'note': 'At least 28 grams per day.',
    },
    'whole_grains_and_potatoes': {
        'percentage': {
            'maximum': 20,
        },
        'note': '',
    },
    'dairy': {
        'percentage': {
            'maximum': 10,
        },
        'note': 'Eat less than 225 grams per week.',
    },
    'minimally_processed_foods': {
        'percentage': {
            'maximum': 10,
        },
        'note': 'This category includes tofu, tempeh, and coarsely ground or sprouted whole grain breads and cereals.',
    },
    'sweets_processed_foods_and_factory_farmed_dairy': {
        'percentage': {
            'maximum': 'Minimal',
        },
        'note': 'You should eat these foods rarely or not at all.',
    },
}

andi_werte_deutsch = {
    'gemüse': {
        'grünes_blattgemüse': {
            'Grünkohl': 1000,
            'Grünkohlblätter': 1000,
            'Senfgrün': 1000,
            'Mangold': 895,
            'Pak Choi': 865,
            'Spinat': 707,
            'Rucola': 604,
            'Römersalat': None,
            'Eisbergsalat': None,
        },
        'festes_grüne_gemüse': {
            'Chinakohl': 714,
            'Brokkoli': 669,
            'Kohl': 238,
            'Rosenkohl': 490,
            'Spargel': 205,
            'Grüne Erbsen': None,
            'Grüne Bohnen': None,
            'Zucchini': None,
        },
        'nicht_grünes_gemüse': {
            'Radieschen': 554,
            'Zwiebeln': 136,
            'Paprika': 265,
            'Pilze': 238,
            'Tomaten': 186,
            'Blumenkohl': 315,
            'Karotten': None,
            'Gurken': None,
            'Knoblauch': None,
            'Kartoffeln': None,
        },
    },
    'früchte': {
        'Erdbeeren': 212,
        'Granatapfel': 193,
        'Brombeeren': 178,
        'Pflaumen': 157,
        'Himbeeren': 145,
        'Blaubeeren': 130,
        'Papaya': 118,
        'Orangen': 109,
        'Cantaloupe': 100,
        'Äpfel': None,
        'Bananen': None,
        'Pfirsiche': None,
        'Birnen': None,
        'Ananas': None,
        'Trauben': None,
        'Mango': None,
        'Wassermelone': None,
    },
    'bohnen_und_hülsenfrüchte': {
        'Linsen': 104,
        'Pinto Bohnen': 101,
        'Nierenbohnen': 100,
        'Schwarze Bohnen': 100,
        'Kichererbsen': 78,
        'Sojabohnen': None,
        'Weiße Bohnen': None,
        'Erbsen': None,
        'Limabohnen': None,
    },
    'nüsse_und_samen': {
        'Leinsamen': 103,
        'Chiasamen': 101,
        'Sesamsamen': 74,
        'Sonnenblumenkerne': 78,
        'Mandeln': 46,
        'Paranüsse & Pekannüsse': 124,
        'Pistazien, ungesalzen': 48,
        'Mandeln & Erdnüsse, ungesalzen': 38,
        'Walnüsse': 34,
        'Haselnüsse': 32,
        'Cashewnüsse, ungesalzen': 27,
        'Pinienkerne': 26,
        'Macadamianüsse, ungesalzen': 17,
        'Leinsamen & Sesamsamen': 65,
        'Kürbiskerne': 52,
        'Erdnüsse': None,
    },
    'vollkornprodukte_und_kartoffeln': {
        'Haferflocken': 53,
        'Brauner Reis': 41,
        'Quinoa': 21,
        'Vollweizen': 17,
        'Gerste': 43,
        'Kleie Flocken': 64,
        'Wildreis, gekocht': 43,
        'Gekeimtes Getreidebrot': 39,
        'Vollkornbrot': 30,
        'Vollweizenbagel': 25,
        'Müsli': 22,
        'Vollkorn-Maismehl': 22,
        'Roggenbrot': 20,
        'Vollweizenpasta, gekocht': 19,
        'Weißbrot & Weißnudeln': 18,
        'Couscous, gekocht': 15,
        'Tortilla, Mehl/Mais': 14,
        'Weißer Reis & Reiskuchen': 12,
        'Kartoffeln': None,
        'Süßkartoffeln': None,
        'Buchweizen': None,
        'Amaranth': None,
        'Hirse': None,
    },
    'milchprodukte': {
        'Milch, fettarm 1%': 28,
        'Naturjoghurt, fettarm': 24,
        'Schokoladenmilch': 19,
        'Fruchtjoghurt, fettarm': 15,
        'Hartkäse': 15,
        'Hüttenkäse': 13,
        'Eiscreme/Joghurt, gefroren': 9,
        'Butter': None,
        'Sahne': None,
        'Sauerrahm': None,
        'Griechischer Joghurt': None,
        'Ei': 27,
    },
    'milchersatz': {
        'Sojamilch': 33,
        'Mandelmilch': 19,
        'Reismilch': 10,
        'Hafermilch': None,
        'Kokosmilch': None,
    },
    'fast_food': {
        'Käsepizza': 17,
        'Fast Food Cheeseburger': 11,
        'Pommes Frites': 7,
    },
    'snacks': {
        'Dunkle Schokoladenriegel': 34,
        'Milchschokoladenriegel': 21,
        'Popcorn, luftgepoppt, ohne Salz': 16,
        'Harte Brezeln, gesalzen': 13,
        'Schokoladenpudding': 11,
        'Müsliriegel': 11,
        'Kartoffelchips & Maischips': 10,
        'Schokoladenkekse, fertig zum Essen': 7,
        'Gummibären': None,
        'Cracker': None,
        'Reiskuchen': None,
        'Eiscreme': None,
    },
    'alkohol': {
        'Bier': 7,
        'Wein': 3,
    }
}

andi_empfehlungen_deutsch = {
    'gemüse': {
        'prozentsatz': {
            'minimum': 30,
            'maximum': 60,
        },
        'notiz': 'Zur Hälfte roh, zur Hälfte gekocht.',
    },
    'obst': {
        'prozentsatz': {
            'minimum': 10,
            'maximum': 40,
        },
        'notiz': 'Täglich 3–5 Portionen frisches Obst.',
    },
    'bohnen_und_hülsenfrüchte': {
        'prozentsatz': {
            'minimum': 10,
            'maximum': 40,
        },
        'notiz': 'Mindestens 85 Gramm täglich.',
    },
    'nüsse_und_samen': {
        'prozentsatz': {
            'minimum': 10,
            'maximum': 40,
        },
        'notiz': 'Mindestens 28 Gramm pro Tag.',
    },
    'vollkornprodukte_und_kartoffeln': {
        'prozentsatz': {
            'maximum': 20,
        },
        'notiz': '',
    },
    'milchprodukte': {
        'prozentsatz': {
            'maximum': 10,
        },
        'notiz': 'Weniger als 225 Gramm pro Woche essen.',
    },
    'minim_verarbeitete_lebensmittel': {
        'prozentsatz': {
            'maximum': 10,
        },
        'notiz': 'Diese Kategorie beinhaltet Tofu, Tempeh und grob gemahlenes oder gekeimtes Vollkornbrot und Müsli.',
    },
    'süssigkeiten_verarbeitete_lebensmittel': {
        'prozentsatz': {
            'maximum': 'Minimal',
        },
        'notiz': 'Diese Lebensmittel sollten Sie selten oder gar nicht essen.',
    },
}



food_names = [food for category in andi_scores.values() for food in category.keys()]
#food_names_deutsch = [food for category in andi_werte_deutsch.values() for food in category.keys()]
unwanted_foods = ["grünes_blattgemüse", "festes_grüne_gemüse", "nicht_grünes_gemüse"]
food_names_deutsch = [food for category in andi_werte_deutsch.values() 
                    for food in category.keys() 
                    if food not in unwanted_foods]
